language: ruby
before_install:
- gem update --system
- gem install bundler
after_success:
- CI=true TRAVIS=true coveralls --verbose
deploy:
  provider: heroku
  api_key:
    secure: NDbul4xYMqFV/squNpQdA+2XESUUBb19RSfca7LPJJxln0pIvd9cLG/kCNDWDaZ/Jhl6bK24ZaPbKLZ1z7dkDGuUN4fjfqH+RbntPQk08ZiiMfOPOFiKuf/+EkzurHydkm2lD9wSA8KNlPsMNJrQQkMaJC8VUMlfWi/3ZIahkuO8+OIzyeUFR0gBE5BhjXUAXi4njj9DFWdRhFOF2Z139MEe6r+vhRaDfN15n6B79Bv9KKBIkNi6v+UUM4+Cu0QoOBKSjxY7oj9+aZtJ5hmxhHy6kTn4zTlN6DyP2J5bJ7d1UbmbYPTRTt6MfGa0regd+2aPB+IcHU9ktCbwDvsfAH6aTomjQK6yjBgpvkpHbsO3R1Vj1H8ZxhBjml74NVFIAhpucURXYhzon+Y0uoQwxhn+tXpKFgwVyS2VFgxrJs0pgbR9/NZl9WI/gX9jYV73AFdKrWOibFfT8t+cHrTmEIBD8W3+n+Tg+gQZIHZ01ODYhz/jHVQLLTxiIfZWfXrRCMeK5NsgZAoqjBXZwakPTnJOQJ1eViyPWai1142bHNb56PyvAB/I4+s5GQ5TTSSL0xGyXRV0NN0HvVB3THFTR1EFCLp50kocFKbTwd/+7q8lhbfVcMhaH+nFupK1Ttj0XOdnHkGeBOh3AvGt5H3rtlmAWPLRiImrfgUy29kqpnc=
  app: matome-nanj
